name: ai_tags_remover
description: Dart/flutter tool to remove all AI-related invisible (hidden) symbols from the project
version: 0.7.0
repository: https://github.com/iBog/ai_tags_remover

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.9.1
  args: ^2.7.0
  logging: ^1.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.26.2

executables:
  ai_tags_remover: main
  ai_tags_remove: main

scripts:
  analyze: "dart run ai_tags_remover"